# Generated by Django 6.0.2 on 2026-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='status',
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
